services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"  
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - API_TOKEN=${API_TOKEN}
    depends_on:
      - neo4j
